// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: profession.proto

package position_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Profession) Reset() {
	*x = Profession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profession_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profession) ProtoMessage() {}

func (x *Profession) ProtoReflect() protoreflect.Message {
	mi := &file_profession_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profession.ProtoReflect.Descriptor instead.
func (*Profession) Descriptor() ([]byte, []int) {
	return file_profession_proto_rawDescGZIP(), []int{0}
}

func (x *Profession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateProfessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateProfessionRequest) Reset() {
	*x = CreateProfessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profession_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProfessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfessionRequest) ProtoMessage() {}

func (x *CreateProfessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profession_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfessionRequest.ProtoReflect.Descriptor instead.
func (*CreateProfessionRequest) Descriptor() ([]byte, []int) {
	return file_profession_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProfessionId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ProfessionId) Reset() {
	*x = ProfessionId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profession_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfessionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfessionId) ProtoMessage() {}

func (x *ProfessionId) ProtoReflect() protoreflect.Message {
	mi := &file_profession_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfessionId.ProtoReflect.Descriptor instead.
func (*ProfessionId) Descriptor() ([]byte, []int) {
	return file_profession_proto_rawDescGZIP(), []int{2}
}

func (x *ProfessionId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllProfessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset_ int32  `protobuf:"varint,1,opt,name=offset_,json=offset,proto3" json:"offset_,omitempty"`
	Limit_  int32  `protobuf:"varint,2,opt,name=limit_,json=limit,proto3" json:"limit_,omitempty"`
	Search  string `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *GetAllProfessionRequest) Reset() {
	*x = GetAllProfessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profession_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllProfessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProfessionRequest) ProtoMessage() {}

func (x *GetAllProfessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profession_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProfessionRequest.ProtoReflect.Descriptor instead.
func (*GetAllProfessionRequest) Descriptor() ([]byte, []int) {
	return file_profession_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllProfessionRequest) GetOffset_() int32 {
	if x != nil {
		return x.Offset_
	}
	return 0
}

func (x *GetAllProfessionRequest) GetLimit_() int32 {
	if x != nil {
		return x.Limit_
	}
	return 0
}

func (x *GetAllProfessionRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type GetAllProfessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Professions []*Profession `protobuf:"bytes,1,rep,name=professions,proto3" json:"professions,omitempty"`
	Count       int32         `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetAllProfessionResponse) Reset() {
	*x = GetAllProfessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profession_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllProfessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProfessionResponse) ProtoMessage() {}

func (x *GetAllProfessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profession_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProfessionResponse.ProtoReflect.Descriptor instead.
func (*GetAllProfessionResponse) Descriptor() ([]byte, []int) {
	return file_profession_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllProfessionResponse) GetProfessions() []*Profession {
	if x != nil {
		return x.Professions
	}
	return nil
}

func (x *GetAllProfessionResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_profession_proto protoreflect.FileDescriptor

var file_profession_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x0a,
	0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2d,
	0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1e, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x61, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x5f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x5f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x22, 0x68, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0b,
	0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f,
	0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_profession_proto_rawDescOnce sync.Once
	file_profession_proto_rawDescData = file_profession_proto_rawDesc
)

func file_profession_proto_rawDescGZIP() []byte {
	file_profession_proto_rawDescOnce.Do(func() {
		file_profession_proto_rawDescData = protoimpl.X.CompressGZIP(file_profession_proto_rawDescData)
	})
	return file_profession_proto_rawDescData
}

var file_profession_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_profession_proto_goTypes = []interface{}{
	(*Profession)(nil),               // 0: genproto.Profession
	(*CreateProfessionRequest)(nil),  // 1: genproto.CreateProfessionRequest
	(*ProfessionId)(nil),             // 2: genproto.ProfessionId
	(*GetAllProfessionRequest)(nil),  // 3: genproto.GetAllProfessionRequest
	(*GetAllProfessionResponse)(nil), // 4: genproto.GetAllProfessionResponse
}
var file_profession_proto_depIdxs = []int32{
	0, // 0: genproto.GetAllProfessionResponse.professions:type_name -> genproto.Profession
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_profession_proto_init() }
func file_profession_proto_init() {
	if File_profession_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_profession_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profession_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProfessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profession_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfessionId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profession_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllProfessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profession_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllProfessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_profession_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_profession_proto_goTypes,
		DependencyIndexes: file_profession_proto_depIdxs,
		MessageInfos:      file_profession_proto_msgTypes,
	}.Build()
	File_profession_proto = out.File
	file_profession_proto_rawDesc = nil
	file_profession_proto_goTypes = nil
	file_profession_proto_depIdxs = nil
}
